apiVersion: v1
kind: Service
metadata:
   name: influxdb-service
   labels:
      app: influxdb
spec:
  selector:
      app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  type: ClusterIP